import React from 'react';

import { Localized } from "@fluent/react";

import DebugAccountNewSummary from './debug_account_new_summary';

import mailApi from 'gelam/main-frame-setup';

/**
 * Cronsync-centered debug view.
 *
 * Upon entry we:
 * - Register for the "newMessagesUpdate"
 * - Ask the backend to flush the current newness track status.
 *
 * Our display and actions:
 * - We have a big "force cronsync" button that triggers a cronsync.
 * - For each account we show the current summary payload generated by the
 *   backend.  For now our felam implementation is designed to produce exactly
 *   what gaia mail wants so we can just copy the code in.
 * - We show a "clear" button to explicitly request that the new tracking be
 *   cleared
 */
export default class DebugCronsync extends React.Component {
  getInitialState() {
    return {
      newAggr: null
    };
  }

  componentDidMount() {
    mailApi.on('newMessagesUpdate', this.onNewMessagesUpdate);
    mailApi.flushNewAggregates();
  }

  componentWillUnmount() {
    mailApi.removeListener('newMessagesUpdate', this.onNewMessagesUpdate);
  }

  onNewMessagesUpdate(newAggr) {
    this.setState({ newAggr });
  }

  render() {
    let perAccountDivs = [];
    let newAggr = this.state.newAggr;
    if (newAggr) {
      for (let [accountId, perAccountData] of newAggr) {
        perAccountDivs.push(
          <DebugAccountNewSummary
            key={ accountId }
            mailApi = { mailApi }
            accountId={ accountId }
            newData={ perAccountData }
            />
        );
      }
    }

    return (
      <div className="debug-cronsync-pane">
        <div className="debug-cronsync-actions">
          <button onClick={ this.forceCronSync }><Localized
            id='forceCronSync'
            />
          </button>
          <button onClick={ this.forceFlushNew }><Localized
            id='forceFlushNew'
            />
          </button>
        </div>
        <div className="debug-cronsync-data-dumps">
          { perAccountDivs }
        </div>
      </div>
    );
  }

  forceCronSync() {
    mailApi.debugForceCronSync({});
  }

  forceFlushNew() {
    mailApi.flushNewAggregates();
  }
};
